services:
  app:
    build:
      context: .
      target: dev
    container_name: app
    working_dir: /app
    volumes:
      - .:/app

  # release:
  #   build: .
  #   container_name: release
  #   working_dir: /app
